nodeLinker: node-modules

npmRegistryServer: "https://nexus.ria.ee/repository/npm-registry/"
phantomjs_cdnurl: "https://nexus.ria.ee/repository/github-raw-proxy/Medium/phantomjs/releases/download/v2.1.1/"

logFilters:
  - level: info
