compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - level: info

nodeLinker: node-modules

npmRegistryServer: "https://nexus.example.ee/repository/npm-registry/"


yarnPath: .yarn/releases/yarn-4.9.2.cjs
